---
Name: simple-pdf-preview
---

SilverStripe\Assets\File:
  extensions:
    - SimplePdfPreviewImageExtension

SimplePdfPreviewImageExtension:
    dependencies:
      generator: %$SimplePdfPreviewImagickGenerator
      folderToSave: "Uploads"
      imagePrefix: "pdf-preview"

Injector:
  SimplePdfPreviewImagickGenerator:
    class: SimplePdfPreviewImagickGenerator